Fixed #82 - Paths positional argument
adamchainz/multilint pull request #83
Opened 2018-09-28 08:14 UTC by arthurio

2018-09-28 17:00 UTC, adamchainz requested changes
Looking good, please also add a note in HISTORY.rst and a test

2018-09-28 17:00 UTC, adamchainz commented on multilint/__init__.py
> +        settings['paths'] = paths
I'd prefer it if we went the other way and set `paths` from `settings['paths']` if `args.paths` is empty, then passed `paths` in below. This way we aren't mutating `settings`.

2018-09-28 17:01 UTC, adamchainz commented
(Test edit `tox.ini` and add a line like `multilint setup.py multilint/`)

2018-09-30 08:43 UTC, adamchainz approved these changes

2018-09-30 08:44 UTC, merged

2018-09-30 08:48 UTC, adamchainz commented
Released in version 2.4.0! https://pypi.org/project/multilint/
Thanks, enjoy.

2018-09-30 15:59 UTC, arthurio commented
Thanks for the quick turnaround!